## Test new way to implement Hubbard Hamiltonian
In order to understand the equivalence of our and aqua hubbard hamiltonian implementation 
let's make these checks:
* hamiltonian length - composition
* results

https://qiskit.org/documentation/_modules/qiskit/chemistry/fermionic_operator.html

In [1]:
from qiskit import QuantumCircuit, execute, Aer, IBMQ
from qiskit.compiler import transpile, assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
import numpy as np
import qiskit
from qiskit import *
from qiskit import Aer
from qiskit.quantum_info import Pauli
from qiskit.aqua.operators import WeightedPauliOperator
from qiskit.aqua.algorithms import ExactEigensolver
from qiskit.aqua.operators.op_converter import to_matrix_operator
from qiskit.chemistry.fermionic_operator import *

 h2(i,j,k,l) --> adag_i adag_k a_l a_j

i = l, k =j 

In [ ]:
H2 = [0i,3j,0k,3l] = adag_0 adag_0 a_3 a_3 = - adag_0 a_0 adag_3 a_3

In [ ]:
H2 = [1,2,1,2] = adag_0 adag_2 a_2 a_0 =  adag_0 a_0 adag_2 a_2

In [ ]:
H2 = [0i,3j,3k,0l] = adag_0 adag_3 a_0 a3 = - adag0 a_0 adag_3 a_3 = -n0 n3

cinetico hopping 1 corpo  h1 
potenziale due corpi h2 
0   1  2  3 
nnlist=[[0,1],[2,3]]

      1u 2u 2d 1d
 
 new: 1d 2d 2u 1u

    n1u       n1d        +     n2u          n2d     --> 0-1 + 2-3
(adag_0 a0) * (adag_3 a3)  + (adag_1 a1) (adag_2 a2)

new: 

          Ha              +         Hb 

adag_0 adag_3 a_0 a_3 = - Ha 
adag_1 adag_2 a1 a2 = -Hb
Ht = Ha + Hb
-Ht 

In [41]:
t=1
U=1

In [95]:
#second quantization hamiltonian from iteration:
nnlist=[[0,1],[2,3]] ## here we define the mapping (0-1)#1 specie / (2-4)# second specie
nnlist1=[[0,3],[1,2]]
L=4

h1=np.zeros((L,L))
h2=np.zeros((L,L,L,L))

for p in nnlist:
    i=p[0]
    j=p[1]
    h1[i,j]=t
    h1[j,i]=t
for a in nnlist1:
    i=a[0]
    j=a[1]
    if i == 0: 
        h2[i,j,j,i]=U 
    else:
        h2[i,j,j,i]=-U 

print(h1)


[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [96]:
len(H)

16

In [97]:
#h1

In [98]:
#h2

In [99]:
#second quantization hamiltonian from from calculation

In [100]:
#############SPIN HAMILTONIAN FROM AQUA
hamiltonian=FermionicOperator(h1,h2) 
# Build the spin hamiltonian using JW transformation
hamiltonian=hamiltonian.mapping('jordan_wigner')
print(hamiltonian)


/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/weighted_pauli_operator.py:118: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months after that release date. You should use the Pauli.num_qubits method instead.
  return self._paulis[0][1].numberofqubits
/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/weighted_pauli_operator.py:118: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months after that release date. You should use the Pauli.num_qubits method instead.
  return self._paulis[0][1].numberofqubits
/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/weighted_pauli_operator.py:118: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months a

Representation: paulis, qubits: 4, size: 10


/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/weighted_pauli_operator.py:118: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months after that release date. You should use the Pauli.num_qubits method instead.
  return self._paulis[0][1].numberofqubits
/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/weighted_pauli_operator.py:118: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months after that release date. You should use the Pauli.num_qubits method instead.
  return self._paulis[0][1].numberofqubits
/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/weighted_pauli_operator.py:118: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months a

In [101]:
print(hamiltonian.to_dict())

{'paulis': [{'label': 'IIYY', 'coeff': {'real': 0.5, 'imag': 0.0}}, {'label': 'IIXX', 'coeff': {'real': 0.5, 'imag': 0.0}}, {'label': 'YYII', 'coeff': {'real': 0.5, 'imag': 0.0}}, {'label': 'XXII', 'coeff': {'real': 0.5, 'imag': 0.0}}, {'label': 'ZIII', 'coeff': {'real': 0.25, 'imag': 0.0}}, {'label': 'IIIZ', 'coeff': {'real': 0.25, 'imag': 0.0}}, {'label': 'ZIIZ', 'coeff': {'real': -0.25, 'imag': 0.0}}, {'label': 'IZII', 'coeff': {'real': -0.25, 'imag': 0.0}}, {'label': 'IIZI', 'coeff': {'real': -0.25, 'imag': 0.0}}, {'label': 'IZZI', 'coeff': {'real': 0.25, 'imag': 0.0}}]}


In [ ]:
#############SPIN HAMILTONIAN from calculation

In [ ]:
############################ EVOLUTION ############################################

In [8]:
## Create the initial state
#to add from beginning
q_reg = QuantumRegister(4)
c_reg = ClassicalRegister(4)
state = QuantumCircuit(q_reg,c_reg)
state.x(1)
state.x(0)


In [9]:
#time evolution using aqua
# Generate the time evolution (just test)
evo_ham = hamiltonian.evolve(state_in=state, evo_time=np.pi/2, num_time_slices=1,
               expansion_mode='trotter', expansion_order=3)

/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/common.py:258: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months after that release date. You should use the Pauli.num_qubits method instead.
  state_registers = QuantumRegister(pauli_list[0][1].numberofqubits)
/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/common.py:273: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months after that release date. You should use the Pauli.num_qubits method instead.
  n_qubits = pauli[1].numberofqubits
/Users/it058990/opt/anaconda3/envs/qiskit_new/lib/python3.8/site-packages/qiskit/aqua/operators/common.py:273: DeprecationWarning: The Pauli.numberofqubits method is deprecated as of 0.13.0, and will be removed no earlier than 3 months after that release date. You sho

In [16]:
print(evo_ham.decompose())

      ┌─────────────┐┌──────────┐                                       »
q0_0: ┤ U3(pi,0,pi) ├┤ U2(0,pi) ├───────────────────────────────────────»
      ├─────────────┤├──────────┤                                       »
q0_1: ┤ U3(pi,0,pi) ├┤ U2(0,pi) ├──■─────────────────────────────■──────»
      └─────────────┘└──────────┘┌─┴─┐                         ┌─┴─┐    »
q0_2: ───────────────────────────┤ X ├──■────────────────■─────┤ X ├────»
        ┌──────────┐             └───┘┌─┴─┐┌──────────┐┌─┴─┐┌──┴───┴───┐»
q0_3: ──┤ U2(0,pi) ├──────────────────┤ X ├┤ U1(pi/2) ├┤ X ├┤ U2(0,pi) ├»
        └──────────┘                  └───┘└──────────┘└───┘└──────────┘»
c0_0: ══════════════════════════════════════════════════════════════════»
                                                                        »
c0_1: ══════════════════════════════════════════════════════════════════»
                                                                        »
c0_2: ════════════════════════════════

In [17]:
print('circuit_depth',evo_ham.decompose().depth())
print('circuit_depth',evo_ham.decompose().count_ops())

circuit_depth 28
circuit_depth OrderedDict([('cx', 16), ('u3', 10), ('u2', 8), ('u1', 4)])
